global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000'] 
    metrics_path: '/metrics'

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:8000']
    metrics_path: '/metrics'

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']