services:
  # ==================
  # Auth service
  # ==================
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env 
    environment:
      - DATABASE_URL=mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}/${AUTH_DB}?authSource=admin
      - AUTH_DB=${AUTH_DB}
    depends_on:
      mongo:
        condition: service_healthy
        
  # ==================
  # Users service
  # ==================
  users-service:
    build: ./services/users-service
    container_name: users-service
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}/${USERS_DB}?authSource=admin
      - USERS_DB=${USERS_DB}
    depends_on:
      mongo:
        condition: service_healthy

  # ==================
  # Shared MongoDB
  # ==================
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${DB_USER}", "--password", "${DB_PASS}", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 5
      start_period: 10s

  # ==================
  # Prometheus
  # ==================
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - auth-service
      - users-service
    restart: unless-stopped

  # ==================
  # Grafana 
  # ==================
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    depends_on:
      - prometheus
    restart: unless-stopped

  # ==================
  # Alertmanager
  # ==================
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"

volumes:
  mongo_data: {}
  grafana-data: {}