services:
  # ==================
  # Auth service
  # ==================
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env 
    environment:
      - DATABASE_URL=mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}/${AUTH_DB}?authSource=admin
      - AUTH_DB=${AUTH_DB}
    depends_on:
      mongo:
        condition: service_healthy
        
  # ==================
  # Users service
  # ==================
  users-service:
    build: ./services/users-service
    container_name: users-service
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}/${USERS_DB}?authSource=admin
      - USERS_DB=${USERS_DB}
    depends_on:
      mongo:
        condition: service_healthy

  # ==================
  # Shared MongoDB
  # ==================
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${DB_USER}", "--password", "${DB_PASS}", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo_data: {}