name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' 
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, users-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./services/${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        working-directory: ./services/${{ matrix.service }}
        run: |
          pip install flake8
          flake8 app --max-line-length=120

      - name: Run tests
        working-directory: ./services/${{ matrix.service }}
        run: |
          echo "Sem testes definidos ainda"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tag
        id: vars
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')
          if [[ "$TAG" == "" ]]; then TAG="latest"; fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ env.TAG }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
